### ISSUE TITLE
ModuleNotFoundError: No module named 'analysis'

### ISSUE THREAD

**Issue by Chenrf1121** [anuragajay/decision-diffuser#4]
When I run `python train`, there is a error: 

>  Traceback (most recent call last):
>   File "train.py", line 3, in <module>
>     from analysis import RUN
> ModuleNotFoundError: No module named 'analysis'

How do I address this, and I don't find any class named `RUN`.

**Comment by 360ZMEM** [comment]
Here the `analysis` is not a package of python. To solve this, you can include the `code` folder of the project into the PYTHONPATH of the environment variables. Besides, you can also create a setup.py as follow:
```
from setuptools import setup, find_packages

setup(
  name = 'ddiffuser',
  packages = find_packages(),
)
```
and execute `pip install -e .`.

**Comment by Niloiv111** [comment]
I met the same problem, and I tried methods you just mentioned, but they didn't work. @360ZMEM

**Comment by zl911120** [comment]
export PYTHONPATH=/path/to/decision-diffuser/（here is your absolute path of code）

**Comment by retroactively** [comment]
export PYTHONPATH=/path/to/decision-diffuser/code
