### ISSUE TITLE
ImportError: cannot import name 'instr' from 'ml_logger'

### ISSUE THREAD

**Issue by Niloiv111** [anuragajay/decision-diffuser#5]
There's a problem when I run train.py. It shows that ImportError: cannot import name 'instr' from 'ml_logger'. Besides, it also cannot import 'needs_relaunch'.

**Comment by GaoZiHong** [comment]
I also have the same problem. have you solved it?

**Comment by ritvikpasham** [comment]
Also running into the same issue.

**Comment by talhazaidi13** [comment]
I resolved this issue after installing the following versions in enviornment:
    - ml_logger==0.8.69 
    
    After this again specify the following versions as described in enviornment.
    - jaynes==0.8.11 
    - params_proto==2.9.6

**Comment by Niloiv111** [comment]
> I resolved this issue after installing the following versions in enviornment: - ml_logger==0.8.69
> 
> ```
> After this again specify the following versions as described in enviornment.
> - jaynes==0.8.11 
> - params_proto==2.9.6
> ```

It works, thank for your reply
